# Generated by Django 4.2 on 2023-04-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
